# Generated by Django 4.0.2 on 2022-02-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAndSellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='email_linked',
            field=models.CharField(default=123, max_length=75),
            preserve_default=False,
        ),
    ]
