# Generated by Django 4.0.2 on 2022-02-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminAndSellers', '0002_seller_email_linked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='email_linked',
            new_name='mail_linked',
        ),
    ]
