# Generated by Django 4.0.2 on 2022-02-26 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminAndSellers', '0003_rename_email_linked_seller_mail_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='user_linked',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
