# Generated by Django 4.0.2 on 2022-02-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminAndSellers', '0004_alter_seller_user_linked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='mail_linked',
        ),
    ]
